site_name: PixTrail Documentation
site_description: Documentation for PixTrail - GPS Photo to GPX Tracker
site_author: Suki Tsubaki
repo_url: https://github.com/sukitsubaki/pixtrail
repo_name: sukitsubaki/pixtrail
copyright: Documentation written by Yuki Shimizu

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share

nav:
  - Home: index.md
  - Installation & Getting Started:
    - Installation: installation.md
    - Getting Started: getting-started.md
  - User Guide:
    - Usage: usage.md
    - Web Interface: web-interface.md
    - Command Line Interface: cli.md
    - Troubleshooting: troubleshooting.md
    - FAQ: faq.md
  - Development:
    - Overview: development/index.md
    - Module Structure: development/module-structure.md
    - CSS Architecture: development/css-architecture.md
    - Testing: development/testing.md
  - Visualization:
    - Overview: visualization/index.md
    - Heat Map: visualization/heatmap.md
    - Marker Clustering: visualization/clustering.md
    - Statistics and Charts: visualization/statistics.md
  - Tutorials:
    - Overview: tutorials/index.md
    - Photo Journey: tutorials/photo-journey.md
    - Batch Processing: tutorials/batch-processing.md
    - Custom Visualizations: tutorials/custom-visualizations.md
  - Architecture: architecture.md
  - Contributing: contributing.md
  - API Reference:
    - Overview: api/index.md
    - Core Modules: api/core.md
    - EXIF Reader: api/exif.md
    - GPX Generator: api/gpx.md
    - Utility Modules: api/utils.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - toc:
      permalink: true

plugins:
  - search
