name: Update Version Numbers

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Extract latest version from CHANGELOG
        id: extract
        run: |
          # Extract the latest version from CHANGELOG.md
          # Skip the Unreleased section and find the first version entry
          VERSION=$(grep -o '## \[[0-9]\+\.[0-9]\+\.[0-9]\+\]' CHANGELOG.md | head -1 | sed 's/## \[\(.*\)\]/\1/')
          
          if [ -z "$VERSION" ]; then
            echo "Failed to extract version from CHANGELOG.md"
            exit 1
          fi
          
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update version numbers
        id: update
        run: |
          VERSION="${{ steps.extract.outputs.version }}"
          echo "Updating files to version $VERSION"
          
          # Initialize update flag
          UPDATED=false
          
          # Update README.md
          if [ -f "README.md" ]; then
            if grep -q 'version-[0-9]\+\.[0-9]\+\.[0-9]\+' README.md; then
              echo "Updating version in README.md"
              sed -i "s/version-[0-9]\+\.[0-9]\+\.[0-9]\+/version-$VERSION/" README.md
              UPDATED=true
            fi
          fi
          
          # Update setup.py
          if [ -f "setup.py" ]; then
            if grep -q 'version="[0-9]\+\.[0-9]\+\.[0-9]\+"' setup.py; then
              echo "Updating version in setup.py"
              sed -i "s/version=\"[0-9]\+\.[0-9]\+\.[0-9]\+\"/version=\"$VERSION\"/" setup.py
              UPDATED=true
            fi
          fi
          
          # Update pyproject.toml
          if [ -f "pyproject.toml" ]; then
            if grep -q 'version = "[0-9]\+\.[0-9]\+\.[0-9]\+"' pyproject.toml; then
              echo "Updating version in pyproject.toml"
              sed -i "s/version = \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/version = \"$VERSION\"/" pyproject.toml
              UPDATED=true
            fi
          fi
          
          # Update pixtrail/__init__.py
          if [ -f "pixtrail/__init__.py" ]; then
            if grep -q '__version__ = "[0-9]\+\.[0-9]\+\.[0-9]\+"' pixtrail/__init__.py; then
              echo "Updating version in pixtrail/__init__.py"
              sed -i "s/__version__ = \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/__version__ = \"$VERSION\"/" pixtrail/__init__.py
              UPDATED=true
            fi
          fi
          
          # Update the Unreleased link in CHANGELOG.md
          if grep -q '\[unreleased\]: https://github.com/sukitsubaki/pixTrail/compare/[0-9]\+\.[0-9]\+\.[0-9]\+\.\.\.HEAD' CHANGELOG.md; then
            echo "Updating Unreleased link in CHANGELOG.md"
            sed -i "s|\[unreleased\]: https://github.com/sukitsubaki/pixTrail/compare/[0-9]\+\.[0-9]\+\.[0-9]\+\.\.\.HEAD|\[unreleased\]: https://github.com/sukitsubaki/pixTrail/compare/$VERSION...HEAD|" CHANGELOG.md
            UPDATED=true
          fi
          
          # Set output variables
          echo "updated=$UPDATED" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.update.outputs.updated == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Make sure we're on the correct branch
          BRANCH_NAME=$(git symbolic-ref --short HEAD || echo "main")
          echo "Current branch: $BRANCH_NAME"
          
          git add README.md setup.py pyproject.toml pixtrail/__init__.py CHANGELOG.md
          git commit -m "automatic update on push (v${{ steps.extract.outputs.version }})"
          git push origin $BRANCH_NAME
